/* USERS */
export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

/* USERS PROFILE */
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL"

/**
 * add user
 */
export const ADD_NEW_USER = "ADD_NEW_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"

/**
 * Edit user
 */
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

/**
 * Delete user
 */
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

/* EXPERS */
export const GET_EXPERTS = "GET_EXPERTS"
export const GET_EXPERTS_SUCCESS = "GET_EXPERTS_SUCCESS"
export const GET_EXPERTS_FAIL = "GET_EXPERTS_FAIL"

/* CHANGE STATUS EXPERS */
export const PUT_STATUS_EXPERTS = "PUT_STATUS_EXPERTS"
export const PUT_STATUS_EXPERTS_SUCCESS = "PUT_STATUS_EXPERTS_SUCCESS"
export const PUT_STATUS_EXPERTS_FAIL = "PUT_STATUS_EXPERTS_FAIL"

/* ADD GUEST */
export const ADD_NEW_GUEST = "ADD_NEW_GUEST"
export const ADD_NEW_GUEST_SUCCESS = "ADD_NEW_GUEST_SUCCESS"
export const ADD_NEW_GUEST_FAIL = "ADD_NEW_GUEST_FAIL"
