/* CARS_BRAND */
export const GET_CARS_BRAND = "GET_CARS_BRAND"
export const GET_CARS_BRAND_SUCCESS = "GET_CARS_BRAND_SUCCESS"
export const GET_CARS_BRAND_FAIL = "GET_CARS_BRAND_FAIL"

/* CARS_BRAND DETAIL */
export const GET_CAR_BRAND_DETAIL = "GET_CAR_BRAND_DETAIL"
export const GET_CAR_BRAND_DETAIL_SUCCESS = "GET_CAR_BRAND_DETAIL_SUCCESS"
export const GET_CAR_BRAND_DETAIL_FAIL = "GET_CAR_BRAND_DETAIL_FAIL"

/**
 * add car brand
 */
export const ADD_NEW_CAR_BRAND = "ADD_NEW_CAR_BRAND"
export const ADD_CAR_BRAND_SUCCESS = "ADD_CAR_BRAND_SUCCESS"
export const ADD_CAR_BRAND_FAIL = "ADD_CAR_BRAND_FAIL"

/**
 * Edit car brand
 */
export const UPDATE_CAR_BRAND = "UPDATE_CAR_BRAND"
export const UPDATE_CAR_BRAND_SUCCESS = "UPDATE_CAR_BRAND_SUCCESS"
export const UPDATE_CAR_BRAND_FAIL = "UPDATE_CAR_BRAND_FAIL"

/**
 * Delete car brand
 */
export const DELETE_CAR_BRAND = "DELETE_CAR_BRAND"
export const DELETE_CAR_BRAND_SUCCESS = "DELETE_CAR_BRAND_SUCCESS"
export const DELETE_CAR_BRAND_FAIL = "DELETE_CAR_BRAND_FAIL"
