/* GROUP SERVICE LIST */
export const GET_GROUP_SERVICE = "GET_GROUP_SERVICE"
export const GET_GROUP_SERVICE_SUCCESS = "GET_GROUP_SERVICE_SUCCESS"
export const GET_GROUP_SERVICE_FAIL = "GET_GROUP_SERVICE_FAIL"
