/* CARS_ITEM */
export const GET_CARS_ITEM = "GET_CARS_ITEM"
export const GET_CARS_ITEM_SUCCESS = "GET_CARS_ITEM_SUCCESS"
export const GET_CARS_ITEM_FAIL = "GET_CARS_ITEM_FAIL"

/* GET_CAR_ITEM_BY_PROBLEM */
export const GET_CARS_ITEM_BY_PROBLEM = "GET_CARS_ITEM_BY_PROBLEM"
export const GET_CARS_ITEM_BY_PROBLEM_SUCCESS =
  "GET_CARS_ITEM_BY_PROBLEM_SUCCESS"
export const GET_CARS_ITEM_BY_PROBLEM_FAIL = "GET_CARS_ITEM_BY_PROBLEM_FAIL"

/* CARS_ITEM DETAIL */
export const GET_CAR_ITEM_DETAIL = "GET_CAR_ITEM_DETAIL"
export const GET_CAR_ITEM_DETAIL_SUCCESS = "GET_CAR_ITEM_DETAIL_SUCCESS"
export const GET_CAR_ITEM_DETAIL_FAIL = "GET_CAR_ITEM_DETAIL_FAIL"

/**
 * add car ITEM
 */
export const ADD_NEW_CAR_ITEM = "ADD_NEW_CAR_ITEM"
export const ADD_CAR_ITEM_SUCCESS = "ADD_CAR_ITEM_SUCCESS"
export const ADD_CAR_ITEM_FAIL = "ADD_CAR_ITEM_FAIL"

/**
 * Edit car ITEM
 */
export const UPDATE_CAR_ITEM = "UPDATE_CAR_ITEM"
export const UPDATE_CAR_ITEM_SUCCESS = "UPDATE_CAR_ITEM_SUCCESS"
export const UPDATE_CAR_ITEM_FAIL = "UPDATE_CAR_ITEM_FAIL"

/**
 * Delete car ITEM
 */
export const DELETE_CAR_ITEM = "DELETE_CAR_ITEM"
export const DELETE_CAR_ITEM_SUCCESS = "DELETE_CAR_ITEM_SUCCESS"
export const DELETE_CAR_ITEM_FAIL = "DELETE_CAR_ITEM_FAIL"
