/* Run Script Customer */
export const RUN_SCRIPT_CUSTOMER = "RUN_SCRIPT_CUSTOMER"
export const RUN_SCRIPT_CUSTOMER_SUCCESS = "RUN_SCRIPT_CUSTOMER_SUCCESS"
export const RUN_SCRIPT_CUSTOMER_FAIL = "RUN_SCRIPT_CUSTOMER_FAIL"

/* Run Script Remove Customer */
export const RUN_SCRIPT_REMOVE_CUSTOMER = "RUN_SCRIPT_REMOVE_CUSTOMER"
export const RUN_SCRIPT_REMOVE_CUSTOMER_SUCCESS =
  "RUN_SCRIPT_REMOVE_CUSTOMER_SUCCESS"
export const RUN_SCRIPT_REMOVE_CUSTOMER_FAIL = "RUN_SCRIPT_REMOVE_CUSTOMER_FAIL"

/* Run Script Booking */
export const RUN_SCRIPT_BOOKING = "RUN_SCRIPT_BOOKING"
export const RUN_SCRIPT_BOOKING_SUCCESS = "RUN_SCRIPT_BOOKING_SUCCESS"
export const RUN_SCRIPT_BOOKING_FAIL = "RUN_SCRIPT_BOOKING_FAIL"

/* Run Remove Script Booking */
export const RUN_REMOVE_SCRIPT_BOOKING = "RUN_REMOVE_SCRIPT_BOOKING"
export const RUN_REMOVE_SCRIPT_BOOKING_SUCCESS =
  "RUN_REMOVE_SCRIPT_BOOKING_SUCCESS"
export const RUN_REMOVE_SCRIPT_BOOKING_FAIL = "RUN_REMOVE_SCRIPT_BOOKING_FAIL"

/* Run Script CheckIn */
export const RUN_SCRIPT_CHECKIN = "RUN_SCRIPT_CHECKIN"
export const RUN_SCRIPT_CHECKIN_SUCCESS = "RUN_SCRIPT_CHECKIN_SUCCESS"
export const RUN_SCRIPT_CHECKIN_FAIL = "RUN_SCRIPT_CHECKIN_FAIL"

/* Run Script CheckIn */
export const RUN_SCRIPT_DIAGNOSE_ORDER = "RUN_SCRIPT_DIAGNOSE_ORDER"
export const RUN_SCRIPT_DIAGNOSE_ORDER_SUCCESS =
  "RUN_SCRIPT_DIAGNOSE_ORDER_SUCCESS"
export const RUN_SCRIPT_DIAGNOSE_ORDER_FAIL = "RUN_SCRIPT_DIAGNOSE_ORDER_FAIL"

/* Run Script Confirm Paid */
export const RUN_SCRIPT_CONFIRM_PAID_ORDER = "RUN_SCRIPT_CONFIRM_PAID_ORDER"
export const RUN_SCRIPT_CONFIRM_PAID_ORDER_SUCCESS =
  "RUN_SCRIPT_CONFIRM_PAID_ORDER_SUCCESS"
export const RUN_SCRIPT_CONFIRM_PAID_ORDER_FAIL =
  "RUN_SCRIPT_CONFIRM_PAID_ORDER_FAIL"

/* Run Script Done */
export const RUN_SCRIPT_DONE_ORDER = "RUN_SCRIPT_DONE_ORDER"
export const RUN_SCRIPT_DONE_ORDER_SUCCESS = "RUN_SCRIPT_DONE_ORDER_SUCCESS"
export const RUN_SCRIPT_DONE_ORDER_FAIL = "RUN_SCRIPT_DONE_ORDER_FAIL"

/* Run Script CheckOut */
export const RUN_SCRIPT_CHECKOUT_ORDER = "RUN_SCRIPT_CHECKOUT_ORDER"
export const RUN_SCRIPT_CHECKOUT_ORDER_SUCCESS =
  "RUN_SCRIPT_CHECKOUT_ORDER_SUCCESS"
export const RUN_SCRIPT_CHECKOUT_ORDER_FAIL = "RUN_SCRIPT_CHECKOUT_FAIL"
