/* SYMPTOMS LIST */
export const GET_SYMPTOMS_LIST = "GET_SYMPTOMS_LIST"
export const GET_SYMPTOMS_LIST_SUCCESS = "GET_SYMPTOMS_LIST_SUCCESS"
export const GET_SYMPTOMS_LIST_FAIL = "GET_SYMPTOMS_LIST_FAIL"

/* SYMPTOMS DETAIL */
export const GET_SYMPTOMS_DETAIL = "GET_SYMPTOMS_DETAIL"
export const GET_SYMPTOMS_DETAIL_SUCCESS = "GET_SYMPTOMS_DETAIL_SUCCESS"
export const GET_SYMPTOMS_DETAIL_FAIL = "GET_SYMPTOMS_DETAIL_FAIL"

/**
 * Add symptoms
 */
export const ADD_NEW_SYMPTOMS = "ADD_NEW_SYMPTOMS"
export const ADD_SYMPTOMS_SUCCESS = "ADD_SYMPTOMS_SUCCESS"
export const ADD_SYMPTOMS_FAIL = "ADD_SYMPTOMS_FAIL"

/**
 * Edit symptoms
 */
export const UPDATE_SYMPTOMS = "UPDATE_SYMPTOMS"
export const UPDATE_SYMPTOMS_SUCCESS = "UPDATE_SYMPTOMS_SUCCESS"
export const UPDATE_SYMPTOMS_FAIL = "UPDATE_SYMPTOMS_FAIL"

/**
 * Delete symptoms
 */
export const DELETE_SYMPTOMS = "DELETE_SYMPTOMS"
export const DELETE_SYMPTOMS_SUCCESS = "DELETE_SYMPTOMS_SUCCESS"
export const DELETE_SYMPTOMS_FAIL = "DELETE_SYMPTOMS_FAIL"
