//const accessToken =
//"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImFkbWluIiwiYWRtaW4iOnRydWUsImp0aSI6ImQ2MTEwYzAxLWMwYjUtNDUzNy1iNDZhLTI0NTk5Mjc2YjY1NiIsImlhdCI6MTU5MjU2MDk2MCwiZXhwIjoxNTkyNTY0NjE5fQ.QgFSQtFaK_Ktauadttq1Is7f9w0SUtKcL8xCmkAvGLw"
const accessToken =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJqdGkiOiIwOTgwZWQzNS1iYzhlLTQwOTYtYmU5ZS1kNmViNWRjNThiNDUiLCJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMTgiLCJyb2xlIjoiQUQiLCJuYmYiOjE2Nzg0NjIzNzUsImV4cCI6MTcxMDA4NDc3NSwiaWF0IjoxNjc4NDYyMzc1fQ.XXq6Te9wYzaE-BUyS45KTzJOhAHrhQmzDcegfwf_cYY"
export default accessToken
