/* CATEGORY SERVICE LIST */
export const GET_CATEGORY_SERVICE = "GET_CATEGORY_SERVICE"
export const GET_CATEGORY_SERVICE_SUCCESS = "GET_CATEGORY_SERVICE_SUCCESS"
export const GET_CATEGORY_SERVICE_FAIL = "GET_CATEGORY_SERVICE_FAIL"
