/* Get System Configurations */
export const GET_SYSTEM_CONFIGURATIONS = "GET_SYSTEM_CONFIGURATIONS"
export const GET_SYSTEM_CONFIGURATIONS_SUCCESS =
  "GET_SYSTEM_CONFIGURATIONS_SUCCESS"
export const GET_SYSTEM_CONFIGURATIONS_FAIL = "GET_SYSTEM_CONFIGURATIONS_FAIL"

/* Get Booking Slot */
export const GET_BOOKING_SLOT = "GET_BOOKING_SLOT"
export const GET_BOOKING_SLOT_SUCCESS = "GET_BOOKING_SLOT_SUCCESS"
export const GET_BOOKING_SLOT_FAIL = "GET_BOOKING_SLOT_FAIL"

/* Get Car In Garage */
export const GET_CAR_IN_GARAGE = "GET_CAR_IN_GARAGE"
export const GET_CAR_IN_GARAGE_SUCCESS = "GET_CAR_IN_GARAGE_SUCCESS"
export const GET_CAR_IN_GARAGE_FAIL = "GET_CAR_IN_GARAGE_FAIL"

/* Put Config System */
export const PUT_CONFIG_SYSTEM = "PUT_CONFIG_SYSTEM"
export const PUT_CONFIG_SYSTEM_SUCCESS = "PUT_CONFIG_SYSTEM_SUCCESS"
export const PUT_CONFIG_SYSTEM_FAIL = "PUT_CONFIG_SYSTEM_FAIL"
