/* IMPORT DATA */
export const IMPORT_DATA_EXCEL = "IMPORT_DATA_EXCEL"
export const IMPORT_DATA_EXCEL_SUCCESS = "IMPORT_DATA_EXCEL_SUCCESS"
export const IMPORT_DATA_EXCEL_FAIL = "IMPORT_DATA_EXCEL_FAIL"

export const RESET_ERROR_DATA_EXCEL = "RESET_ERROR_DATA_EXCEL"
