/* ORDER SERVICE LIST */
export const GET_ORDER_SERVICE_LIST = "GET_ORDER_SERVICE_LIST"
export const GET_ORDER_SERVICE_LIST_SUCCESS = "GET_ORDER_SERVICE_LIST_SUCCESS"
export const GET_ORDER_SERVICE_LIST_FAIL = "GET_ORDER_SERVICE_LIST_FAIL"

/* ORDER SERVICE LIST BY STATUS */
export const GET_ORDER_SERVICE_LIST_BY_STATUS =
  "GET_ORDER_SERVICE_LIST_BY_STATUS"
export const GET_ORDER_SERVICE_LIST_BY_STATUS_SUCCESS =
  "GET_ORDER_SERVICE_LIST_BY_STATUS_SUCCESS"
export const GET_ORDER_SERVICE_LIST_BY_STATUS_FAIL =
  "GET_ORDER_SERVICE_LIST_BY_STATUS_FAIL"

/* ORDER_SERVICE DETAIL */
export const GET_ORDER_SERVICE_DETAIL = "GET_ORDER_SERVICE_DETAIL"
export const GET_ORDER_SERVICE_DETAIL_SUCCESS =
  "GET_ORDER_SERVICE_DETAIL_SUCCESS"
export const GET_ORDER_SERVICE_DETAIL_FAIL = "GET_ORDER_SERVICE_DETAIL_FAIL"

/* RECOMMEND ORDER SERVICE  */
export const PUT_ORDER_SERVICE = "PUT_ORDER_SERVICE"
export const PUT_ORDER_SERVICE_SUCCESS = "PUT_ORDER_SERVICE_SUCCESS"
export const PUT_ORDER_SERVICE_FAIL = "PUT_ORDER_SERVICE_FAIL"

/* ASSIGN EXPERT */
export const PUT_ASSIGN_EXPERT = "PUT_ASSIGN_EXPERT"
export const PUT_ASSIGN_EXPERT_SUCCESS = "PUT_ASSIGN_EXPERT_SUCCESS"
export const PUT_ASSIGN_EXPERT_FAIL = "PUT_ASSIGN_EXPERT_FAIL"

/* AUTO ASSIGN EXPERT */
export const PUT_AUTO_ASSIGN_EXPERT = "PUT_AUTO_ASSIGN_EXPERT"
export const PUT_AUTO_ASSIGN_EXPERT_SUCCESS = "PUT_AUTO_ASSIGN_EXPERT_SUCCESS"
export const PUT_AUTO_ASSIGN_EXPERT_FAIL = "PUT_AUTO_ASSIGN_EXPERT_FAIL"

/* EXPERT INTENDED TIME */
export const GET_EXPERTS_INTENDED_TIME = "GET_EXPERTS_INTENDED_TIME"
export const GET_EXPERTS_INTENDED_TIME_SUCCESS =
  "GET_EXPERTS_INTENDED_TIME_SUCCESS"
export const GET_EXPERTS_INTENDED_TIME_FAIL = "GET_EXPERTS_INTENDED_TIME_FAIL"

/* EXPERT INTENDED TIME BY SERVICE*/
export const GET_EXPERTS_INTENDED_TIME_BY_SERVICE_TIME =
  "GET_EXPERTS_INTENDED_TIME_BY_SERVICE_TIME"
export const GET_EXPERTS_INTENDED_TIME_BY_SERVICE_TIME_SUCCESS =
  "GET_EXPERTS_INTENDED_TIME_BY_SERVICE_TIME_SUCCESS"
export const GET_EXPERTS_INTENDED_TIME_BY_SERVICE_TIME_FAIL =
  "GET_EXPERTS_INTENDED_TIME_BY_SERVICE_TIME_FAIL"

/* STATUS LOG */
export const GET_STATUS_LOG = "GET_STATUS_LOG"
export const GET_STATUS_LOG_SUCCESS = "GET_STATUS_LOG_SUCCESS"
export const GET_STATUS_LOG_FAIL = "GET_STATUS_LOG_FAIL"

/* CONFIRM SERVICES */
export const PUT_CONFIRM_SERVICES = "PUT_CONFIRM_SERVICES"
export const PUT_CONFIRM_SERVICES_SUCCESS = "PUT_CONFIRM_SERVICES_SUCCESS"
export const PUT_CONFIRM_SERVICES_FAIL = "PUT_CONFIRM_SERVICES_FAIL"

/* CONFIRM & PAID SERVICES */
export const PUT_CONFIRM_PAID_SERVICES = "PUT_CONFIRM_PAID_SERVICES"
export const PUT_CONFIRM_PAID_SERVICES_SUCCESS =
  "PUT_CONFIRM_PAID_SERVICES_SUCCESS"
export const PUT_CONFIRM_PAID_SERVICES_FAIL = "PUT_CONFIRM_PAID_SERVICES_FAIL"

/* PRIORITY */
export const PUT_PRIORITY_SERVICES = "PUT_PRIORITY_SERVICES"
export const PUT_PRIORITY_SERVICES_SUCCESS = "PUT_PRIORITY_SERVICES_SUCCESS"
export const PUT_PRIORITY_SERVICES_FAIL = "PUT_PRIORITY_SERVICES_FAIL"

/* CHECKOUT */
export const CHECKOUT_SERVICES = "CHECKOUT_SERVICES"
export const CHECKOUT_SERVICES_SUCCESS = "CHECKOUT_SERVICES_SUCCESS"
export const CHECKOUT_SERVICES_FAIL = "CHECKOUT_SERVICES_FAIL"

/* COUNT */
export const COUNT_SERVICES = "COUNT_SERVICES"
export const COUNT_SERVICES_SUCCESS = "COUNT_SERVICES_SUCCESS"
export const COUNT_SERVICES_FAIL = "COUNT_SERVICES_FAIL"
