/* BOOKING LIST */
export const GET_BOOKING_LIST = "GET_BOOKING_LIST"
export const GET_BOOKING_LIST_SUCCESS = "GET_BOOKING_LIST_SUCCESS"
export const GET_BOOKING_LIST_FAIL = "GET_BOOKING_LIST_FAIL"

/* BOOKING DETAIL */
export const GET_BOOKING_DETAIL = "GET_BOOKING_DETAIL"
export const GET_BOOKING_DETAIL_SUCCESS = "GET_BOOKING_DETAIL_SUCCESS"
export const GET_BOOKING_DETAIL_FAIL = "GET_BOOKING_DETAIL_FAIL"

/**
 * Check-in
 */

export const CHECKIN_BOOKING = "CHECKIN_BOOKING"
export const CHECKIN_BOOKING_SUCCESS = "CHECKIN_BOOKING_SUCCESS"
export const CHECKIN_BOOKING_FAIL = "CHECKIN_BOOKING_FAIL"

/**
 * Check-in QR-CODE
 */

export const CHECKIN_QRCODE = "CHECKIN_QRCODE"
export const CHECKIN_QRCODE_SUCCESS = "CHECKIN_QRCODE_SUCCESS"
export const CHECKIN_QRCODE_FAIL = "CHECKIN_QRCODE_FAIL"

/**
 * Get Booking By Date
 */

export const GET_BOOKING_LIST_BY_DATE = "GET_BOOKING_LIST_BY_DATE"
export const GET_BOOKING_LIST_BY_DATE_SUCCESS =
  "GET_BOOKING_LIST_BY_DATE_SUCCESS"
export const GET_BOOKING_LIST_BY_DATE_FAIL = "GET_BOOKING_LIST_BY_DATE_FAIL"

/**
 * Add Booking
 */
export const ADD_NEW_BOOKING = "ADD_NEW_BOOKING"
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS"
export const ADD_BOOKING_FAIL = "ADD_BOOKING_FAIL"

/**
 * Edit Booking
 */
export const UPDATE_BOOKING = "UPDATE_BOOKING"
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS"
export const UPDATE_BOOKING_FAIL = "UPDATE_BOOKING_FAIL"

/**
 * Delete Booking
 */
export const DELETE_BOOKING = "DELETE_BOOKING"
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS"
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL"
