/* CARS PROBLEM */
export const GET_CARS_PROBLEM = "GET_CARS_PROBLEM"
export const GET_CARS_PROBLEM_SUCCESS = "GET_CARS_PROBLEM_SUCCESS"
export const GET_CARS_PROBLEM_FAIL = "GET_CARS_PROBLEM_FAIL"

/* CARS PROBLEM DETAIL */
export const GET_CAR_PROBLEM_DETAIL = "GET_CAR_PROBLEM_DETAIL"
export const GET_CAR_PROBLEM_DETAIL_SUCCESS = "GET_CAR_PROBLEM_DETAIL_SUCCESS"
export const GET_CAR_PROBLEM_DETAIL_FAIL = "GET_CAR_PROBLEM_DETAIL_FAIL"

/* CARS PROBLEM BY MODEL */
export const GET_CAR_PROBLEM_BY_MODEL = "GET_CAR_PROBLEM_BY_MODEL"
export const GET_CAR_PROBLEM_BY_MODEL_SUCCESS =
  "GET_CAR_PROBLEM_BY_MODEL_SUCCESS"
export const GET_CAR_PROBLEM_BY_MODEL_FAIL = "GET_CAR_PROBLEM_BY_MODEL_FAIL"

/**
 * add car PROBLEM
 */
export const ADD_NEW_CAR_PROBLEM = "ADD_NEW_CAR_PROBLEM"
export const ADD_CAR_PROBLEM_SUCCESS = "ADD_CAR_PROBLEM_SUCCESS"
export const ADD_CAR_PROBLEM_FAIL = "ADD_CAR_PROBLEM_FAIL"

/**
 * Edit car PROBLEM
 */
export const UPDATE_CAR_PROBLEM = "UPDATE_CAR_PROBLEM"
export const UPDATE_CAR_PROBLEM_SUCCESS = "UPDATE_CAR_PROBLEM_SUCCESS"
export const UPDATE_CAR_PROBLEM_FAIL = "UPDATE_CAR_PROBLEM_FAIL"

/**
 * Delete car PROBLEM
 */
export const DELETE_CAR_PROBLEM = "DELETE_CAR_PROBLEM"
export const DELETE_CAR_PROBLEM_SUCCESS = "DELETE_CAR_PROBLEM_SUCCESS"
export const DELETE_CAR_PROBLEM_FAIL = "DELETE_CAR_PROBLEM_FAIL"

/**
 * Reset car PROBLEM
 */

export const RESET_CARS_PROBLEM = "RESET_CARS_PROBLEM"
